name: linkdin_auth_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  linkedin_login: ^3.0.5
  dio: ^5.7.0
  hooks_riverpod:
  flutter_riverpod:
  flutter_secure_storage: ^9.2.2
  http_interceptor: ^2.0.0
  url_launcher: ^6.3.0
  uni_links:
  app_links: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
